# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fast"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = false
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Water sensitive items list.
	water_sensitive = ["minecraft:campfire", "minecraft:fire_charge", "minecraft:lava_bucket", "minecraft:redstone_torch", "minecraft:soul_campfire", "minecraft:soul_torch", "minecraft:torch"]
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

